config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :users
  resources :flats
  resources :bookings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/home', to: 'pages#home'
  resources :flats, only: [:index, :new, :create]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to flats_path, notice: 'Flat was successfully created.'
    else
      render :new
    end
  end

  private

  def flat_params
    # Define the permitted parameters for creating a new flat
    params.require(:flat).permit(:attribute1, :attribute2, :attribute3)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def offers
  end

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/index.html.erb
<h1>Available Flats</h1>

<ul>
  <% @flats.each do |flat| %>
    <li><%= link_to flat.title, flat_path(flat) %></li>
  <% end %>
</ul>

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= form_for @flat do |f| %>
  <!-- Form fields for flat attributes -->
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <!-- Add more form fields as needed -->

  <div>
    <%= f.submit 'Create Flat' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentall</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Flats', flats_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to 'My Bookings', bookings_path %></li>
      <li><%= link_to 'Publish an Offer', new_flat_path %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    <% end %>
  </ul>
</nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to RentAll Your Airbnb Clone!</h1>
<p>Find and book unique accommodations around the world.</p>